# Generated by Django 4.2.6 on 2023-10-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_department_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='department',
        ),
    ]
