# Generated by Django 4.2.6 on 2023-10-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_assignment_job_assignment_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
